name: builder
description: "Builds the projects in a-light-win"
inputs:
  zig_project:
    description: |
      The path to the zig project to build, test or check.
      If not provided, the zig actions are skipped.
  podman_project:
    description: |
      The path to the podman project to build, test or check.
      If not provided, the podman actions are skipped.
  GITHUB_TOKEN:
    description: "The GitHub token to use for pushing to the GitHub Container Registry"
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup just
      uses: extractions/setup-just@v2
    - name: Setup global just
      shell: bash
      run: |
        mkdir -p $HOME/.config/
        ln -snf "$GITHUB_ACTION_PATH" $HOME/.config/just
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Setup podman
      shell: bash
      run: |
        just -g podman setup

    - name: Test zig project
      uses: a-light-win/builder/.github/actions/zig-test@main
      if: ${{ github.event_name == 'pull_request' && inputs.zig_project != '' }}
      with:
        working_directory: ${{ inputs.zig_project }}

    - name: Release zig project
      uses: a-light-win/builder/.github/actions/zig-release@main
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.zig_project != '' }}
      with:
        working_directory: ${{ inputs.zig_project }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: build container image
      uses: a-light-win/builder/.github/actions/podman-release@main
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.podman_project != '' }}
      with:
        working_directory: ${{ inputs.podman_project }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
