name: zig-release
description: "pack and upload the zig project on tags"
inputs:
  working_directory:
    description: The root path of the zig project
    required: true
  GITHUB_TOKEN:
    description: "The Github token"
    required: true
runs:
  using: composite
  steps:
    - name: packing the zig project
      run: |
        just -g zig pack-all
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: uploading assets
      run: |
        just -g zig upload "${{ github.repository }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
