set unstable := true

# build/clean docker images of debian
mod debian 'debian/Justfile'
# build/clean docker images of zig
mod zig 'zig/Justfile'
# build/clean docker images of nfpm
mod nfpm 'nfpm/Justfile'
