
# test the bash scripts
[no-cd]
test:
  bats --tap "{{ source_dir() }}/bash/tests"

# test and generate the coverage report
[no-cd]
cov:
  mkdir -p dist/kcov
  kcov --exclude-path=/usr/,/tmp dist/kcov bats --tap "{{ source_dir() }}/bash/tests"
