#!/usr/bin/env bash

podman-run() {
    podman run --rm \
        --env-host \
        -v $(pwd):$(pwd) \
        -w $(pwd) \
        "$@"
}

podman-setup() {
    # debian os family
    which apt-get
    if [ $$? -eq 0 ]; then
        sudo apt-get update && sudo apt-get install -y podman
        return $?
    fi

    # archlinux
    which pacman
    if [ $$? -eq 0 ]; then
        sudo pacman -Sy podman
        return $?
    fi

    echo >&2 "Error: unsupported os family"
    cat /etc/os-release >&2
    return 1
}
