#!/usr/bin/env bash

# translate the architecture name to the Go architecture name
go-arch() {
  local arch="$1"

  case "$arch" in
  x86_64) echo "amd64" ;;
  aarch64) echo "arm64" ;;
  *) echo "$arch" ;;
  esac
}
