#!/usr/bin/env bash

export ZIG_TAG="${ZIG_VERSION}${ZIG_VERSION_RELEASE}"
export ZIG_IMAGE="$BUILDER_REPOSITORY/zig"
export ZIG_IMAGE_FULL="$ZIG_IMAGE:$ZIG_TAG"

ZIG_GLOBAL_CACHE="${ZIG_GLOBAL_CACHE:=${HOME}/.cache/zig}"
# realease: one of safe, fast and small, default to safe
ZIG_RELEASE="${ZIG_RELEASE:-safe}"

podman-zig() {
    podman-run -v "${ZIG_GLOBAL_CACHE}:${ZIG_GLOBAL_CACHE}" \
        "${ZIG_IMAGE_FULL}" \
        zig "$@"
}

zig-build() {
    local arch="$1"

    should-skip-arch "$arch" && return 0

    echo "Building project with zig for $arch ..."
    # target: one of x86_64-linux-musl, aarch64-linux-musl
    local target="$arch-linux-musl"

    podman-zig build \
        --release="${ZIG_RELEASE}" \
        -Dtarget="${target}"
}

zig-clean() {
    local output_dir="${PKG_TARGET:-zig-out}"

    echo "Cleaning the binaries in ${output_dir}/bin ..."
    rm -rf "${output_dir}/bin/"*

    echo "Cleaning the libraries in ${output_dir}/lib ..."
    rm -rf "${output_dir}/lib/"*

    echo "Cleaning the zig cache in .zig-cache ..."
    rm -rf .zig-cache/*
}
