---
name: zig-test
description: checks and test the zig project on pull requests
inputs:
  working_directory:
    description: The path to the zig project.
    required: true
runs:
  using: composite
  steps:
    - name: Test zig project
      run: |
        just -g zig test ${{ inputs.zig_project }}
      shell: bash
      working-directory: ${{ inputs.zig_project }}
