set unstable := true

self := (just_executable() +
         ' -f ' + source_file()
        )

[no-cd, script('bash'), positional-arguments]
upload repo *files:
  if [ -z "$PKG_VERSION" ]; then
    echo "PKG_VERSION is required"
    exit 1
  fi

  grep -q '^[^\s/!]\+/[^\s/!]\+$' <<< '{{ repo }}'
  if [ $? -ne 0 ]; then
    echo "repo should be in 'OWNER/REPO' format: {{ repo }}"
    exit 1
  fi

  files=("${@:2}")
  for file in "${files[@]}"; do
    {{ self }} upload-one "{{ repo }}" "${file}" || exit $?
  done

[private, no-cd, script('bash')]
upload-one repo file:
  if [ ! -e "{{ file }}" ]; then
    echo "File not found: {{ file }}"
    exit 1
  fi

  echo "Uploading {{ file }} to {{ repo }} ..."

  if [ -z "$GITHUB_TOKEN" ]; then
    echo "GITHUB_TOKEN is required"
    exit 1
  fi

  curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "Content-Type: application/octet-stream" \
    "https://uploads.github.com/repos/{{ repo }}/releases/"${PKG_VERSION}"/assets?name={{ file_name(file) }}" \
    --data-binary "@{{ file }}"
