
[no-cd, script('bash')]
release repo:
  source "{{ builtin_bash_functions }}"

  github-release assets_url "{{ repo }}" || exit 1

  nfpm-pkg-files files || exit 1
  if [ "${#files[@]}" -ne 0 ]; then
    github-upload "${assets_url}" "${files[@]}"
  else
    echo "No files to upload"
  fi
