name: podman-release
description: "Create container images for"
inputs:
  working_directory:
    description: The root path of the docker file directory
    required: true
runs:
  using: composite
  steps:
    - name: Build container image
      run: |
        just -g podman pack-all
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${GITHUB_TOKEN}
    - name: Push container image
      run: |
        just -g podman upload
      shell: bash
      working-directory: ${{ inputs.working_directory }}
