set unstable := true

import '../../lib/podman.just'
import '../../dockerfiles/vars.just'

# Build a zig program
[no-cd, script('bash'), positional-arguments]
build target release='safe' *args:
  # target: one of x86_64-linux-musl, aarch64-linux-musl
  # realease: one of safe, fast and small
  {{ podman_run }} -v `pwd`/zig-out/.cache:/root/.cache {{ zig_image_full }} \
    zig build --release="{{ release }}" -Dtarget="{{ target }}" "${@:3}"
