set unstable := true

import '../../lib/podman.just'
import '../../dockerfiles/vars.just'

zig_global_cache := cache_directory() / 'zig'

# Build a zig program
[no-cd, script('bash'), positional-arguments]
build target release='safe' *args='':
  # target: one of x86_64-linux-musl, aarch64-linux-musl
  # realease: one of safe, fast and small
  {{ podman_run }} -v "{{ zig_global_cache }}:{{ zig_global_cache }}" {{ zig_image_full }} \
    zig build --release="{{ release }}" -Dtarget="{{ target }}" {{ if args != '' { "${@:3}" } else { '' } }}
