---
name: Resusable Image Release Workflow
on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
jobs:
  build-image:
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, format('refs/tags/{0}-', inputs.module)) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build ${{ inputs.module }} image
        uses: a-light-win/builder@main
        with:
          podman_project: ${{ github.workspace }}/dockerfiles/${{ inputs.module }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
