---
name: Resusable Image Release Workflow
on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
jobs:
  build-image:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/${{ inputs.module }}-')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build ${{ inputs.module }} image
        uses: a-light-win/builder@main
        with:
          action_ref: ${{ github.ref_name }}
          podman_project: ${{ github.workspace }}/dockerfiles/${{ inputs.module }}
