---
name: Image Release
on:
  push:
    tags:
      - "*"
jobs:
  build-debian-image:
    uses: ./.github/workflows/_image-release.yaml
    with:
      module: debian

  build-zig-image:
    uses: ./.github/workflows/_image-release.yaml
    with:
      module: zig

  build-nfpm-image:
    uses: ./.github/workflows/_image-release.yaml
    with:
      module: nfpm
